# Generated by Django 3.0.7 on 2020-06-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200622_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
